---
version: "3.5"

services:

  geocontrib:
    container_name: "geocontrib_django"
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - geocontrib/geocontrib-with-georchestra.env
    ports:
      - "5000:5000"
    volumes:
      - geocontrib_media:/home/apprunner/geocontrib_app/media
      - geocontrib_static:/home/apprunner/geocontrib_app/static
    depends_on:
      - geocontrib-db

  # ---------------------------------------------------------------- #
  geocontrib-db:
    container_name: "geocontrib_db"
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=geocontrib
      - POSTGRES_PASSWORD=geocontrib
      - POSTGRES_DB=geocontrib
    volumes:
      - geocontrib_data:/var/lib/postgresql/data/

  # ---------------------------------------------------------------- #
  geocontrib-nginx:
    container_name: "geocontrib_nginx"
    build:
      context: nginx
    env_file:
      - geocontrib/geocontrib-with-georchestra.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - geocontrib_media:/opt/geocontrib/media
      - geocontrib_static:/opt/geocontrib/static
    ports:
      - "8000:80"
    depends_on:
      - geocontrib

  # ---------------------------------------------------------------- #
  database:
    image: georchestra/database:20.0.2
    environment:
      - POSTGRES_USER=georchestra
      - POSTGRES_PASSWORD=georchestra
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  # ---------------------------------------------------------------- #
  ldap:
    image: georchestra/ldap:20.0.2
    environment:
        - SLAPD_ORGANISATION=georchestra
        - SLAPD_DOMAIN=georchestra.org
        - SLAPD_PASSWORD=secret
        - SLAPD_LOG_LEVEL=32768 # See https://www.openldap.org/doc/admin24/slapdconfig.html#loglevel%20%3Clevel%3E
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap

  # ---------------------------------------------------------------- #
  georchestra.mydomain.org:
    image: traefik:1.7
    ports:
      - "8888:80"
      - "443:443"
      # uncomment the next line to get a web ui + api at https://georchestra.mydomain.org:8080/traefik/
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/resources/ssl:/etc/traefik/ssl/
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/resources/traefik.toml:/traefik.toml

  # ---------------------------------------------------------------- #
  proxy:
    image: georchestra/security-proxy:20.0.2
    depends_on:
      - ldap
      - database
    volumes:
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"

  # ---------------------------------------------------------------- #
  cas:
    image: georchestra/cas:20.0.2
    depends_on:
      - ldap
    volumes:
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cas"
      - "traefik.frontend.rule=Host:georchestra.mydomain.org;PathPrefix:/cas"

  # ---------------------------------------------------------------- #
  header:
    image: georchestra/header:20.0.2
    volumes:
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=512M

  # ---------------------------------------------------------------- #
  console:
    image: georchestra/console:20.0.2
    depends_on:
      - ldap
      - database
    volumes:
      - ${GEORCHESTRA_DOCKER_PROJECT_ROOT_PATH}/config:/etc/georchestra
    environment:
      - JAVA_OPTIONS=-Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
      - XMS=256M
      - XMX=1G

volumes:
  geocontrib_data:
  geocontrib_media:
  geocontrib_static:
  postgresql_data:
  smtp_maildir:
  ldap_data:
  ldap_config:
